from __future__ import annotations

from app.agents.anomaly_agent import AnomalyAgent
from app.agents.attribution_agent import AttributionAgent
from app.agents.baseline_agent import BaselineAgent
from app.audit.audit_log import AuditLog
from app.db import init_db, sync_alerts, sync_events
from app.eval.harness import build_alerts, evaluate
from app.ingest.synth_generator import generate_events
from app.paths import (
    ALERTS_PATH,
    ASSET_INVENTORY_PATH,
    AUDIT_LOG_PATH,
    CVE_FEED_PATH,
    EVAL_REPORT_PATH,
    EVENTS_PATH,
    ROOT_DIR,
    ensure_dirs,
)
from app.rag.mitre_loader import build_mitre_corpus
from app.rag.chroma_store import persist_chroma_corpus
from app.storage import write_json, write_jsonl


def seed_static_feeds() -> None:
    assets = [
        {"asset_id": "candidate-portal", "name": "Candidate Portal", "criticality": 5, "owner": "Exam Ops"},
        {"asset_id": "proctoring", "name": "Invigilator Portal", "criticality": 4, "owner": "Centre Ops"},
        {"asset_id": "marking", "name": "Examiner Marking Portal", "criticality": 5, "owner": "Evaluation"},
        {"asset_id": "certificate-service", "name": "Certificate Verification Service", "criticality": 4, "owner": "Public Trust"},
        {"asset_id": "auth-db", "name": "Auth DB", "criticality": 5, "owner": "Identity"},
    ]
    # SIMULATED/MOCKED: synthetic CVEs model risk prioritisation without live CVE calls.
    cves = [
        {"cve": "CVE-2026-EXAM-0001", "asset_id": "auth-db", "cvss": 9.4, "exploitability": 0.92, "summary": "Weak session invalidation path in legacy auth middleware.", "related_techniques": ["T1078", "T1110"]},
        {"cve": "CVE-2026-EXAM-0002", "asset_id": "certificate-service", "cvss": 8.1, "exploitability": 0.88, "summary": "Certificate lookup endpoint lacks adaptive throttling.", "related_techniques": ["T1499"]},
        {"cve": "CVE-2026-EXAM-0003", "asset_id": "marking", "cvss": 8.8, "exploitability": 0.78, "summary": "Marking portal file export can over-share script bundles.", "related_techniques": ["T1041", "T1005"]},
        {"cve": "CVE-2026-EXAM-0004", "asset_id": "proctoring", "cvss": 7.2, "exploitability": 0.64, "summary": "Stale proctor device trust token permits lateral portal access.", "related_techniques": ["T1021", "T1078"]},
    ]
    write_json(ASSET_INVENTORY_PATH, assets)
    write_json(CVE_FEED_PATH, cves)


def write_results(report: dict) -> None:
    text = f"""# Aegis-CNI Results

Generated by `python seed.py` / `/eval/report`.

| Metric | Value |
| --- | ---: |
| Dataset rows | {report['dataset_rows']} |
| Labelled attack rows | {report['labelled_attack_rows']} |
| Alert count | {report['alert_count']} |
| Detection rate | {report['detection_rate']:.2%} |
| False positive rate | {report['false_positive_rate']:.2%} |
| ATT&CK technique attribution accuracy | {report['attack_technique_accuracy']:.2%} |
| MTTD | {report['mttd_minutes']} min |
| Manual SOC MTTD baseline | {report['manual_mttd_minutes']} min |
| MTTD improvement | {report['mttd_improvement']}x |
| MTTR | {report['mttr_minutes']} min |
| Manual SOC MTTR baseline | {report['manual_mttr_minutes']} min |
| MTTR improvement | {report['mttr_improvement']}x |
| Autonomous playbook steps | {report['autonomous_playbook_percent']:.1f}% |
| Local ATT&CK techniques | {report.get('mitre_technique_count', 0)} |
| Chroma corpus ready | {report.get('chroma_ready', False)} |

Observed ATT&CK techniques: {', '.join(report['observed_techniques'])}
"""
    (ROOT_DIR / "RESULTS.md").write_text(text, encoding="utf-8")


def main() -> None:
    ensure_dirs()
    init_db()
    if AUDIT_LOG_PATH.exists():
        AUDIT_LOG_PATH.unlink()
    techniques = build_mitre_corpus()
    chroma_ready = persist_chroma_corpus(techniques)
    seed_static_feeds()
    events = generate_events()
    write_jsonl(EVENTS_PATH, [e.model_dump() for e in events])
    sync_events([e.model_dump() for e in events])

    baseline = BaselineAgent().build(events)
    anomaly = AnomalyAgent()
    anomaly.fit(events)
    attribution = AttributionAgent()
    alerts = build_alerts(events, anomaly, attribution)
    report = evaluate(events, alerts, anomaly.threshold)

    write_json(ALERTS_PATH, [a.model_dump() for a in alerts])
    sync_alerts([a.model_dump() for a in alerts])
    write_json(EVAL_REPORT_PATH, {**report, "baseline": baseline, "mitre_technique_count": len(techniques), "chroma_ready": chroma_ready})
    write_results({**report, "mitre_technique_count": len(techniques), "chroma_ready": chroma_ready})
    AuditLog().append(
        actor="seed.py",
        action="seed_demo_dataset",
        justification="Generated deterministic telemetry, ATT&CK corpus, alerts, CVE queue, and benchmark report.",
        blast_radius=0,
        payload={"events": len(events), "alerts": len(alerts), "mitre_techniques": len(techniques), "chroma_ready": chroma_ready},
    )
    print(f"Seeded {len(events)} events, {len(alerts)} alerts, {len(techniques)} MITRE techniques.")


if __name__ == "__main__":
    main()
